# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Favorites"
  pageRef = "favorites"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20